name: gera_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  html: ^0.15.0
  envied: ^1.0.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^1.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
